debug: true

spring:
  security.user:
    name: root
    password: root

  h2.console:
    enabled: true
    settings:
      trace: false
      web-allow-others: false

  datasource:
    url: jdbc:h2:mem:jefree;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

app:
  frontend-url: http://localhost:3000

libs:
  security.web.cors.allowed-origin-patterns: ["http://localhost:*", "https://localhost:*"]