server.forward-headers-strategy: FRAMEWORK

spring:
  config.import: optional:configtree:/run/secrets/
  application.name: JEFREE
  jackson.default-property-inclusion: non_null

  sql.init:
    platform: mysql
    mode: always
#    schema-locations: classpath:/db/schema.sql
#    data-locations: classpath:/db/data.sql
    continue-on-error: true

  data.rest:
    basePath: /api/repository
    defaultPageSize: 20
    maxPageSize: 100
    pageParamName: page
    limitParamName: limit
    sortParamName: sort

  datasource:
    url: jdbc:mysql://${JEFREE_DATABASE_HOST:localhost}:3306/jefree?createDatabaseIfNotExist=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    driverClassName: com.mysql.cj.jdbc.Driver
    name: jefree
    username: ${JEFREE_DATABASE_USER:root}
    password: ${JEFREE_DATABASE_PASSWORD:}
    initializationMode: always
    tomcat:
      max-active: 50
      max-idle: 30
      time-between-eviction-runs-millis: 5000
      min-evictable-idle-time-millis: 20000
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jackson:
    default-property-inclusion: NON_NULL
    parser:
      ALLOW_COMMENTS: true
    serialization:
      write-null-map-values: false
      fail-on-empty-beans: false
      WRITE_DATES_AS_TIMESTAMPS: false
    deserialization:
      accept-single-value-as-array: true
#    date-format: ......RFC3339DateFormat

  security.oauth2.client.registration:
    # GitHub OAuth2 configuration
    github:
      client-id: ${JEFREE_GITHUB_CLIENT_ID}
      client-secret: ${JEFREE_GITHUB_CLIENT_SECRET}
      scope: read:user,user:email
      redirect-uri: ${libs.security.oauth2.redirectUri}

    # Google OAuth2 configuration
    google:
      client-id: ${JEFREE_GOOGLE_CLIENT_ID}
      client-secret: ${JEFREE_GOOGLE_CLIENT_SECRET}
      redirect-uri: ${libs.security.oauth2.redirectUri}

app:
  frontend-url: ${JEFREE_FRONTEND_URL:http://localhost:9080}

libs:
  mailer:
    google:
      client-id: ${JEFREE_GOOGLE_CLIENT_ID}
      client-secret: ${JEFREE_GOOGLE_CLIENT_SECRET}
      refresh-token: ${JEFREE_GOOGLE_REFRESH_TOKEN}
      from-email: ${JEFREE_GOOGLE_FROM_EMAIL}
  security:
    oauth2.redirectUri: "https://{baseHost}{basePort}{basePath}/login/oauth2/code/{registrationId}"
    jwt:
      secret: ${JEFREE_JWT_SECRET:JEFREE}
      expiration: 86400000 # 1 day
      header: Authorization
      prefix: Bearer
    web:
      json-prefix.enabled: false
      cors:
        allowed-origins: ${app.frontend-url}
        allowed-origin-patterns: ["${app.frontend-url}/*"]
        allowed-methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS", "HEAD"]
        max-age: 3600
        # https://en.wikipedia.org/wiki/List_of_HTTP_header_fields
        allowed-headers: [
          # Allowed standard request fields
          "Accept",
          "Accept-Charset",
          "Accept-Datetime",
          "Accept-Encoding",
          "Accept-Language",
          "Access-Control-Request-Method",
          "Access-Control-Request-Headers",
          "Authorization",
          "Cache-Control",
          "Connection",
          "Content-Encoding",
          "Content-Length",
          "Content-MD5",
          "Content-Type",
          "Cookie",
          "Date",
          "Forwarded",
          "From",
          "Host",
          "HTTP2-Settings",
          "If-Match",
          "If-Modified-Since",
          "If-None-Match",
          "If-Range",
          "If-Unmodified-Since",
          "Origin",
          "Pragma",
          "Prefer",
          "Priority",
          "Range",
          "Referer",
          "Transfer-Encoding",
          "User-Agent",
          "Via",

          # Allowed common non-standard request fields
          "X-Requested-With",
          "DNT",
          "X-Forwarded-For",
          "X-Forwarded-Host",
          "X-Forwarded-Proto",
          "Front-End-Https",
          "X-Csrf-Token",
          "X-CSRFToken",
          "X-XSRF-TOKEN",
          "X-Request-ID",
          "X-Correlation-ID",
          "Save-Data",
          "withcredentials",
          "enctype",
          "sec-ch-ua",
          "sec-ch-ua-mobile",
          "sec-ch-ua-platform",
          "sec-fetch-dest",
          "sec-fetch-mode",
          "sec-fetch-site",

          # Implemented as a misunderstanding of the HTTP specifications.
          # Has exactly the same functionality as standard Connection field. Must not be used with HTTP/2
          "Proxy-Connection"
        ]
        exposed-headers: [
          # Allowed standard response fields
          "Access-Control-Allow-Origin",
          "Access-Control-Allow-Credentials",
          "Access-Control-Expose-Headers",
          "Access-Control-Max-Age",
          "Access-Control-Allow-Methods",
          "Access-Control-Allow-Headers",
          "Accept-Patch",
          "Accept-Ranges",
          "Age",
          "Allow",
          "Alt-Svc",
          "Cache-Control",
          "Connection",
          "Content-Disposition",
          "Content-Encoding",
          "Content-Language",
          "Content-Length",
          "Content-Location",
          "Content-MD5",
          "Content-Range",
          "Content-Type",
          "Date",
          "Delta-Base",
          "ETag",
          "Expires",
          "Last-Modified",
          "Link",
          "Location",
          "Pragma",
          "Preference-Applied",
          "Public-Key-Pins",
          "Retry-After",
          "Set-Cookie",
          "Transfer-Encoding",
          "Tk",
          "Vary",
          "Via",
          "Warning",
          "WWW-Authenticate",
          "X-Frame-Options",

          # Allowed common non-standard response fields
          "Content-Security-Policy",
          "X-Content-Security-Policy",
          "X-WebKit-CSP",
          "Refresh",
          "X-Content-Duration",
          "X-Content-Type-Options",
          "X-Request-ID",
          "X-Correlation-ID",
          "X-UA-Compatible",
          "X-XSS-Protection",
          "X-CZ-RESPONSECODE",
          "Clear-Site-Data",
          "x-amz-cf-id",
          "x-amz-cf-pop",
          "x-cache",
        ]