name: jefree-core

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/services/jefree-core/**'
      - 'backend/libs/**'
      - .github/workflows/service-workflow.yml
      - .github/workflows/jefree-core.yml

jobs:
  run:
    uses: ./.github/workflows/service-workflow.yml
    with:
      service: jefree-core